'use strict';
// HYPHA Wave 1.4 — Misconception Engine v0 (theory ship).
//
// Surface the v0.2 lesson body's `common_misconceptions[]` field as classified,
// detectable, repairable artifacts. Three primary functions:
//
//   extractMisconceptions(lessonBody, kpId)
//     Raw strings (LLM-generated by lesson-body-generator.js) → typed records
//     with category + severity + cue_phrases + repair_strategy. Heuristic
//     classifier today; T4_JUDGE upgrade tagged TODO.
//
//   detectMisconceptionInResponse(userResponse, kpMisconceptions)
//     Cheap pre-screen of the student's reply against each misconception's
//     cue_phrases (string includes + regex). Returns the strongest match with
//     a confidence score. Anti-Illusion W1.3 calls this stream from its
//     misconception_repair intervention path.
//
//   repairMisconception(triggered, lessonContext)
//     Produces the tutor-side prompt the LLM injects on the next turn to
//     surgically correct the wrong-prior in 1-2 turns. Per-category template.
//
// Source of misconception text = `lesson-body-generator.js`'s 11-field body
// schema (`body.common_misconceptions: string[2]`, validated 10-200 chars each).
// We do NOT mutate that schema — the engine is a pure read-side reader +
// classifier + detector. Persistence lives in misconception-vault.js as a
// sidecar so multiple slugs can share the same data shape without 11-field
// schema drift.
//
// Categories (per BLUEPRINT.md §7.4 "common misconceptions / wrong analogies /
// surface understanding / dangerous simplification / pseudo-understanding"):
//
//   wrong_analogy            — student maps the concept to a familiar but
//                              structurally incorrect domain ("attention is
//                              like a spotlight" when it's a weighted sum)
//   surface_understanding    — student knows the definition but not the
//                              mechanism ("recursion = function calling
//                              itself" without grasping the base-case trap)
//   dangerous_simplification — student strips a load-bearing nuance, which
//                              works in toy cases and fails in real ones
//                              ("just use UTF-8 for everything")
//   pseudo_understanding     — student performs fluency (Feynman-test
//                              failure: can recite, cannot apply or transfer)

const SEVERITY_LEVELS = Object.freeze(['low', 'medium', 'high', 'critical']);

const CATEGORIES = Object.freeze({
  WRONG_ANALOGY: 'wrong_analogy',
  SURFACE_UNDERSTANDING: 'surface_understanding',
  DANGEROUS_SIMPLIFICATION: 'dangerous_simplification',
  PSEUDO_UNDERSTANDING: 'pseudo_understanding',
});

// Heuristic phrase-banks for cheap classification. T4_JUDGE upgrade (TODO
// W1.4-followup) will replace these with model-grounded classification.
const _ANALOGY_CUES = ['像', '类比', 'like a', 'is like', '相当于', '类似', 'analog', 'metaphor'];
const _SURFACE_CUES = ['就是', '不就是', 'is just', 'merely', 'simply', '定义是', 'by definition'];
const _SIMPLIFICATION_CUES = ['只要', '只需', 'just use', 'always', '永远', '所有', 'every', 'no need to', '不必'];
const _PSEUDO_CUES = ['我懂了', '明白了', 'I understand', 'I get it', 'makes sense', '清楚了'];

// Per-category repair-prompt templates. These are injected into the next
// tutor turn (via LESSON BRIEF appendix in agent.js _buildLessonBriefBlock,
// OR via Anti-Illusion W1.3 misconception_repair intervention path).
const _REPAIR_TEMPLATES = Object.freeze({
  [CATEGORIES.WRONG_ANALOGY]:
    'The student is mapping this concept to a familiar but structurally different domain. ' +
    'Do not lecture. Ask them to push the analogy until it breaks: "if X behaves like Y, ' +
    'then what should happen when [edge-case]?" Their answer will expose the disanalogy. ' +
    'Then offer a structurally faithful frame, anchored in the canonical_example.',

  [CATEGORIES.SURFACE_UNDERSTANDING]:
    'The student knows the words but not the mechanism. Ask them to predict what would ' +
    'happen if [a load-bearing nuance] were removed. Their answer reveals whether they ' +
    'understand the mechanism or just memorized the label. Return to mechanism_explanation, ' +
    'not the definition.',

  [CATEGORIES.DANGEROUS_SIMPLIFICATION]:
    'The student has stripped a nuance that works in the toy case and fails in the real ' +
    'one. Present a concrete instance where the simplification breaks (drawn from sources ' +
    'or canonical_example). Ask them to explain WHY it breaks before you supply the answer.',

  [CATEGORIES.PSEUDO_UNDERSTANDING]:
    'The student is performing fluency. Apply the Feynman test (exit_proof): give them a ' +
    'FRESH case they have not seen and ask them to apply the concept end-to-end without ' +
    'leaning on memorized phrasing. Failure here is data, not shame.',
});

// Heuristic classifier: tag a misconception string with the most plausible
// category based on lexical cues. Returns category + confidence (0..1).
// intentional-placeholder: T4_JUDGE second-pass classifier deferred to
// W1.4-followup per task scope ("category 标注 + T4_JUDGE 二判留 TODO"). The
// heuristic returns a real, deterministic classification today; the upgrade
// path swaps the lexical tally for a 200-token T4_JUDGE call via router.js.
function _classifyHeuristic(text) {
  const s = String(text || '').toLowerCase();
  if (!s) return { category: CATEGORIES.SURFACE_UNDERSTANDING, confidence: 0.2 };
  const tally = {
    [CATEGORIES.WRONG_ANALOGY]: _ANALOGY_CUES.filter(c => s.includes(c.toLowerCase())).length,
    [CATEGORIES.SURFACE_UNDERSTANDING]: _SURFACE_CUES.filter(c => s.includes(c.toLowerCase())).length,
    [CATEGORIES.DANGEROUS_SIMPLIFICATION]: _SIMPLIFICATION_CUES.filter(c => s.includes(c.toLowerCase())).length,
    [CATEGORIES.PSEUDO_UNDERSTANDING]: _PSEUDO_CUES.filter(c => s.includes(c.toLowerCase())).length,
  };
  let best = CATEGORIES.SURFACE_UNDERSTANDING;
  let bestN = -1;
  for (const [k, n] of Object.entries(tally)) {
    if (n > bestN) { best = k; bestN = n; }
  }
  // Confidence: ratio of hits to cue-bank size (capped). 0 hits → 0.25 default
  // (the field is required, so we always emit a category; the confidence
  // signals "this is a guess").
  const conf = bestN === 0 ? 0.25 : Math.min(0.85, 0.4 + bestN * 0.2);
  return { category: best, confidence: conf };
}

// Heuristic severity: short, blunt corrections = lower severity; longer text
// with negation cues = critical. Per W1.3 Anti-Illusion: critical
// misconceptions interrupt the lesson; low ones get a side-note.
function _gradeSeverity(text, category) {
  const s = String(text || '');
  const len = s.length;
  const hasStrongCorrection = /must not|never|完全错|根本不|永远不|critical/i.test(s);
  if (hasStrongCorrection || category === CATEGORIES.DANGEROUS_SIMPLIFICATION) {
    return len > 100 ? 'critical' : 'high';
  }
  if (category === CATEGORIES.PSEUDO_UNDERSTANDING) return 'high';
  if (len < 40) return 'low';
  if (len < 100) return 'medium';
  return 'high';
}

// Cue-phrase generation: extract short n-gram fragments from the misconception
// text that, if the user utters them, signal they're walking into the trap.
// Heuristic today (split on punctuation, take first 3-6 word chunks); upgrade
// path = LLM-generated paraphrastic cues from same T4_JUDGE pass.
function _deriveCuePhrases(text) {
  const s = String(text || '').trim();
  if (!s) return [];
  // Split on Chinese + Latin punctuation, keep clauses ≥ 4 chars / 2 words.
  const clauses = s
    .split(/[。.!?;；，,—–\-]+/)
    .map(c => c.trim())
    .filter(c => c.length >= 4 && c.split(/\s+/).length >= 1);
  // Strip the correction half — misconception entries follow the pattern
  // "<wrong belief> + <sharp correction>" per lesson-body-generator.js:87.
  // We want cue_phrases drawn from the WRONG-belief clause only. Heuristic:
  // first 1-2 clauses are the belief; later clauses are the correction.
  const beliefSide = clauses.slice(0, Math.min(2, clauses.length));
  return beliefSide.slice(0, 4).map(c => c.slice(0, 60));
}

// ---------------------------------------------------------------------------
// extractMisconceptions: read lesson body's common_misconceptions[] → typed
// records. lesson-body-generator.js validates the field is exactly 2 strings,
// each 10-200 chars. We accept any non-empty array gracefully (legacy/older
// bodies may have 1 or 3+).
// ---------------------------------------------------------------------------
function extractMisconceptions(lessonBody, kpId) {
  const raw = (lessonBody && Array.isArray(lessonBody.common_misconceptions))
    ? lessonBody.common_misconceptions
    : [];
  if (raw.length === 0) return [];
  return raw
    .map((text, i) => {
      const t = String(text || '').trim();
      if (!t) return null;
      const { category, confidence } = _classifyHeuristic(t);
      const severity = _gradeSeverity(t, category);
      const cue_phrases = _deriveCuePhrases(t);
      const repair_strategy = _REPAIR_TEMPLATES[category] || _REPAIR_TEMPLATES[CATEGORIES.SURFACE_UNDERSTANDING];
      return {
        id: `${kpId || 'kp-unknown'}-mc-${i + 1}`,
        kp_id: kpId || null,
        text: t,
        category,
        category_confidence: Math.round(confidence * 100) / 100,
        severity,
        cue_phrases,
        repair_strategy,
        // intentional-placeholder: T4_JUDGE second-pass fields left null on
        // first extract per task scope ("category 标注 + T4_JUDGE 二判留 TODO").
        // W1.4-followup writes these via router.executeChat('T4_JUDGE', ...).
        t4_judge_category: null,
        t4_judge_rationale: null,
        t4_judge_at: null,
      };
    })
    .filter(Boolean);
}

// ---------------------------------------------------------------------------
// detectMisconceptionInResponse: cheap pre-screen. Scan userResponse for any
// cue_phrase from any misconception; return strongest hit + confidence. Used
// by W1.3 Anti-Illusion to trigger misconception_repair intervention.
//
// Returns { triggered: misconception_object | null, confidence: 0..1, matches }
// matches[] retained for downstream T4_JUDGE second-pass (TODO).
// ---------------------------------------------------------------------------
function detectMisconceptionInResponse(userResponse, kpMisconceptions) {
  const s = String(userResponse || '').toLowerCase();
  const mcs = Array.isArray(kpMisconceptions) ? kpMisconceptions : [];
  if (!s || mcs.length === 0) {
    return { triggered: null, confidence: 0, matches: [] };
  }
  const hits = [];
  for (const mc of mcs) {
    if (!mc || !Array.isArray(mc.cue_phrases)) continue;
    let hitCount = 0;
    const matchedPhrases = [];
    for (const phrase of mc.cue_phrases) {
      const p = String(phrase || '').trim().toLowerCase();
      if (p.length < 3) continue;
      if (s.includes(p)) {
        hitCount += 1;
        matchedPhrases.push(phrase);
        continue;
      }
      // Loose regex fallback: tolerate whitespace collapse + Chinese / English
      // word-boundary mismatches.
      try {
        const escaped = p.replace(/[.*+?^${}()|[\]\\]/g, '\\$&').replace(/\s+/g, '\\s*');
        const re = new RegExp(escaped, 'i');
        if (re.test(s)) {
          hitCount += 0.6;
          matchedPhrases.push(phrase + ' (loose)');
        }
      } catch (_) { /* malformed phrase — skip */ }
    }
    if (hitCount > 0) {
      // Severity multiplier: critical/high misconceptions are more confident
      // when their cue triggers, so the repair fires earlier in W1.3 budget.
      const severityMult = mc.severity === 'critical' ? 1.0
        : mc.severity === 'high' ? 0.85
        : mc.severity === 'medium' ? 0.65
        : 0.45;
      // Normalize: hit-fraction × severity. Single cue match ≈ 0.4-0.6.
      const denom = Math.max(1, mc.cue_phrases.length);
      const conf = Math.min(0.95, (hitCount / denom) * severityMult + 0.25);
      hits.push({
        misconception: mc,
        confidence: Math.round(conf * 100) / 100,
        matchedPhrases,
        hitCount,
      });
    }
  }
  if (hits.length === 0) return { triggered: null, confidence: 0, matches: [] };
  hits.sort((a, b) => b.confidence - a.confidence);
  const top = hits[0];
  // intentional-placeholder: T4_JUDGE second-pass over `hits` deferred per
  // task scope. The cheap pre-screen returns a real, ranked detection today;
  // W1.4-followup wraps the top hit with a model-grounded confirmation to
  // discard false-positives (cue mentioned vs wrong-prior actually invoked).
  return {
    triggered: top.misconception,
    confidence: top.confidence,
    matches: hits,
  };
}

// ---------------------------------------------------------------------------
// repairMisconception: produce a tutor-side correction prompt. Returns
// { repair_prompt, expected_user_action } so the calling layer (W1.3
// intervention OR agent.js next-turn injector) can wire it into the prompt
// pipeline directly.
// ---------------------------------------------------------------------------
function repairMisconception(triggered, lessonContext) {
  if (!triggered) {
    return { repair_prompt: '', expected_user_action: 'text_explain' };
  }
  const category = triggered.category || CATEGORIES.SURFACE_UNDERSTANDING;
  const tmpl = triggered.repair_strategy || _REPAIR_TEMPLATES[category] || '';
  const ctx = lessonContext || {};
  const thesisLine = ctx.thesis ? `Lesson thesis: ${String(ctx.thesis).slice(0, 200)}` : '';
  const canonicalLine = ctx.canonical_example ? `Canonical example to anchor on: ${String(ctx.canonical_example).slice(0, 200)}` : '';
  const exitProofLine = ctx.exit_proof ? `Feynman test to close on: ${String(ctx.exit_proof).slice(0, 200)}` : '';

  // Pseudo-understanding repairs require a fresh-case test (the student
  // chooses among 3 transfer scenarios); other categories repair through a
  // text explanation. UI in screen-lesson-chat.jsx routes on this field.
  const expectedAction = category === CATEGORIES.PSEUDO_UNDERSTANDING
    ? 'choose_among_3'
    : 'text_explain';

  const lines = [
    `MISCONCEPTION REPAIR (W1.4 — triggered ${category}, severity ${triggered.severity || 'unknown'}):`,
    `Wrong-prior detected: "${String(triggered.text || '').slice(0, 240)}"`,
    `Repair strategy:`,
    tmpl,
    '',
    'Context for the repair:',
    thesisLine,
    canonicalLine,
    exitProofLine,
    '',
    'Next turn: execute the repair surgically in 1-2 exchanges. Do not lecture; ' +
    'do not shame. Return to the main lesson arc once the wrong-prior is ' +
    'replaced with a structurally faithful frame.',
  ].filter(Boolean).join('\n');

  return {
    repair_prompt: lines,
    expected_user_action: expectedAction,
  };
}

module.exports = {
  extractMisconceptions,
  detectMisconceptionInResponse,
  repairMisconception,
  // Surface constants for callers (tests, T4_JUDGE upgrade) without forcing
  // them to maintain parallel enums.
  CATEGORIES,
  SEVERITY_LEVELS,
};
